export enum Emoji {
    SMILE = "😊",
    SAD = "😢",
    SURPRISED = "😮",
    GRIN = "😃",
    WINK = "😉",
    LAUGH = "😆",
    CRY = "😭",
    ANGRY = "😠",
    HEART = "❤️",
    THUMBS_UP = "👍",
    THUMBS_DOWN = "👎",
    STAR = "⭐",
    COOL = "😎",
    KISS = "😘",
    CONFUSED = "😕",
    SLEEPY = "😴",
    THINKING = "🤔",
    PARTY = "🥳",
    ZANY = "🤪",
}

export const emojiMap: Record<string, Emoji> = {
    ":)": Emoji.SMILE,
    ":(": Emoji.SAD,
    ":o": Emoji.SURPRISED,
    ":D": Emoji.GRIN,
    ";)": Emoji.WINK,
    XD: Emoji.LAUGH,
    T_T: Emoji.CRY,
    ">:(": Emoji.ANGRY,
    "<3": Emoji.HEART,
    ":+1:": Emoji.THUMBS_UP,
    ":-1:": Emoji.THUMBS_DOWN,
    "*": Emoji.STAR,
    "B)": Emoji.COOL,
    ":*": Emoji.KISS,
    ":/": Emoji.CONFUSED,
    "-_-": Emoji.SLEEPY,
    ":thinking:": Emoji.THINKING,
    ":party:": Emoji.PARTY,
    ":zany:": Emoji.ZANY,
};
